defaults: &defaults
  app_name: "宝贝丁"
  domain: "baobeiding.com"
  api_domain: "127.0.0.1:3000"
  admin_emails:
    - "xide@qq.com"
  seo:
    title: '儿童装母婴用品导购平台、分享美丽的起点'
    keywords: '宝贝丁、童装、母婴用品'
    description: '宝贝丁是国内专业儿童装、母婴用品导购平台，推荐淘宝、京东、1号店、苏宁等平台最优质的儿童装、母婴用品品牌和产品，与全国妈妈们一起分享和记录孩子的美丽起点。'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
